language: objective-c
script: rake test
before_install:
  - brew update
  - brew upgrade xctool
  - gem install xcpretty --no-document
  - gem install cocoapods --no-document
install:
  - rm -f Tests/Podfile.lock # Workaround CocoaPods/CocoaPods#1623
  - (cd Tests && pod install)
