language: objective-c
env: LANG=en_US.UTF-8
script: rake test
before_install:
  - gem install xcpretty --no-document
  - gem install cocoapods --no-document
install:
  - rm -f Tests/Podfile.lock # Workaround CocoaPods/CocoaPods#1623
  - (cd Tests && pod install)
