xcodeproj 'Resort Tests'
workspace '../Resort'
# inhibit_all_warnings!

def import_pods
  pod 'OCMockito'
  pod 'Expecta'
  pod 'Resort', :path => '../'
end

target :ios do
  platform :ios, '7.0'
  link_with 'iOS Tests'
  import_pods
end

target :osx do
  platform :osx, '10.9'
  link_with 'OS X Tests'
  import_pods
end
